### ISSUE TITLE
JsonSerializationException when calling TvDbClient.SeriesExtended() and data.averageRuntime is null

### ISSUE THREAD

**Issue by snew3687** [HristoKolev/TVdbSharper#34]
For some TV series, a JsonSerializationException occurs when calling TvDbClient.SeriesExtended()  because the averageRuntime is null.

For example, this request:
https://api4.thetvdb.com/v4/series/402602/extended

...returns a response including the following:

```
{
        "isOrderRandomized": false,
        "lastUpdated": "2022-11-11 07:43:55",
        "averageRuntime": null,
}
```

It seems to me that `TvDbSharper.SeriesExtendedRecordDto.AverageRuntime` needs to be of type `int?` rather than `int`.

I thought about submitting a pull request (which I have never done before). However, it appears that this class is generated code...so, applying a manual fix seems not to be the right thing to do. I am guessing that the class needs be regenerated, in some way.

I am guessing that this code is generated from the the TVDB API's JSON schema, like here:
https://thetvdb.github.io/v4-api/#/Series/getSeriesExtended

I don't know much about JSON schema...the schema indicates that `averageRuntime` is an `int`. I don't know how we are supposed to know that this may be nullable.

Anyway, I hope it is useful that I have raised this issue because the issue results in the following exception for my code:

```
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Error converting value {null} to type 'System.Int32'. Path 'data.averageRuntime', line 1, position 617.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TvDbSharper.TvDbClient.Parse[T](Int32 statusCode, String responseJson)
   at TvDbSharper.TvDbClient.<Get>d__12`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Picks03a.Database.Repository.TheTvDbReferenceRepository.<GetTvSeriesAsync>d__7.MoveNext() in C:\gitrepos\picks03c-webapi\src\Picks03a.Database\Repository\TheTvDbReferenceRepository.cs:line 85
```

**Comment by snew3687** [comment]
This issue has been occurring for me for the last several days. Then, today, I tried again, and it is no longer occurring. At least not for television series with id "402602". When I retry a GET of this URL, now:
https://api4.thetvdb.com/v4/series/402602/extended

...the result includes a non-null `averageRuntime` value, like so:

```
{
       ...
        "isOrderRandomized": false,
        "lastUpdated": "2022-11-11 21:10:54",
        "averageRuntime": 52,
        "episodes": null,
       ...

}
```

So, perhaps this not a TvDBSharper issue at all? Perhaps it was a (temporary) issue in the TVDB API itself, and has been resolved?

Or perhaps the issue still exists...but the data has been corrected for this record? I'm not sure how to tell.

**Comment by snew3687** [comment]
OK, I have had a closer look at this now. I can see how the code generator works. It seems to me that `SeriesExtendedRecordDto.AverageRuntime` needs to be nullable. I have created a pull request #35 to fix this issue.

However, the AppVeyer continues build seems to have failed and has blocked my pull request:
https://ci.appveyor.com/project/HristoKolev/tvdbsharper/builds/45359103

Seems to be an issue related to the .NET version, which I don't believe to be a result of the code change that I made. So I'm not sure how to progress this now.

**Comment by HristoKolev** [comment]
Hi there. I had a busy couple of months and kind of neglected this project. I'll take a look at this in the coming days.

**Comment by neogentrics** [comment]
This issue, and the accompanying pull request #35, were 100% correct. The API can return null for averageRuntime, but the DTO class was expecting a non-nullable int.

As part of the project modernization, I have added a new rule to the PropertyOverrides list in the CodeBuilder.cs file. This new rule forces the averageRuntime property on SeriesExtendedRecordDto to be a nullable int?, which resolves the JsonSerializationException.

You can close this as resolved if you wish. The fix was added in commit 95a49d5e8426ca1a6c2365e2d76e8eda09e61bca.
